version: "3.9"
services:
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  api:
    container_name: api
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app:/api

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo

  migration:
    # platform: linux/amd64
    build:
      context: ./backend/db
      dockerfile: ./Dockerfile
